#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}flake8 kapi tests
${PREFIX}isort kapi tests --recursive --check-only
#${PREFIX}mypy kapi tests --ignore-missing-imports
