#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv --ignore kapi/layouts --cov=kapi --cov=tests --cov-report=term-missing ${@}
